
# configuration file for continuous integration testing using travis-ci.org

dist: xenial

language: python

dist:
 - trusty

services:
  - docker

script:
# build Docker container
- docker build -t nnenum .

# run tests
- docker run nnenum
