name: "nnenum"
ami: "ami-0280f3286512b1b99", 
scripts_dir: "vnncomp_scripts"
manual_installation_step: False
run_installation_script_as_root: False
run_post_installation_script_as_root: False
run_toolkit_as_root: False
description: >
  "nnenum (pronounced en-en-en-um) is a high-performance neural network verification tool. Multiple levels of abstraction are used to quickly verify ReLU networks without sacrificing completeness. Analysis combines three types of zonotopes and deeppoly with star set (triangle) overapproximations."